name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress setup
        run: npm install cypress --save-dev

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: dist

  api-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4.15
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: APP-DATABASE
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress setup
        run: npm install cypress --save-dev

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: "API Tests"
        uses: cypress-io/github-action@v6
        with:
          start: node ./dist/index.js
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120
          config-file: cypress.config.ts
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

